config/routes.rb
Rails.application.routes.draw do

  root 'jobs#index'

  match '/jobs/detail', :to => 'jobs#detail', :via => :get
  match '/jobs/complete', :to => 'jobs#complete', :via => :put
  match '/jobs/update_status', :to => 'jobs#update_status', :via => :put
  match '/jobs/change_stage', :to => 'jobs#change_stage', :via => :put
  match '/jobs/update_time', :to => 'jobs#update_time', :via => :put
  match '/jobs/add_sand', :to => 'jobs#add_sand', :via => :put
  match '/jobs/new_job', :to => 'jobs#new_job', :via => :put
  match '/jobs/init_data', :to => 'jobs#init_data', :via => :get

  resources :jobs do

  end

end

app/models/Sand.rb
class Sand < ActiveRecord::Base

end

app/models/Stage.rb
class Stage < ActiveRecord::Base
  belongs_to :job
end

app/models/Status.rb
class Status < ActiveRecord::Base
end

app/models/job.rb
class Job < ActiveRecord::Base
  has_many :stages, dependent: :destroy

  def complete_stage(stage_no, status)
    stage = stages.find_by(stage_no: stage_no)
    # end_time = Time.now.change(:sec => 0)
    end_time = Time.now
    time_diff = end_time - stage.end_time
    stage.update(status_id: status, completed: true, end_time: end_time)

    next_stages = stages.where("stage_no > ?", stage_no)
    if next_stages.present?
      next_stages.each { |next_stage|
        next_stage.update(start_time: next_stage.start_time + time_diff, end_time: next_stage.end_time + time_diff)
      }
    end
  end

  def update_status(stage_no, status)
    stage = stages.find_by(stage_no: stage_no)
    stage.update_attribute('status_id', status)
  end

  def update_time(stage_no, add_time)
    stage = stages.find_by(stage_no: stage_no)
    # end_time = Time.now.change(:sec => 0)
    end_time = stage.end_time + add_time.minutes
    if stage.start_time >= end_time
      return
    end
    stage.update(end_time: end_time)

    next_stages = stages.where("stage_no > ?", stage_no)
    if next_stages.present?
      next_stages.each { |next_stage|
        next_stage.update(start_time: next_stage.start_time + add_time.minutes, end_time: next_stage.end_time + add_time.minutes)
      }
    end
  end

  def add_sand(stage_no, sand_id, flag)
    stage = stages.find_by(stage_no: stage_no)
    sands = stage.sands.split(',')

    if flag == "0" #remove
      sands.delete(sand_id)
    else #add
      sands.push(sand_id) unless sands.include?(sand_id.to_s)
    end

    stage.update(sands: sands.join(','))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    @jobs = Job.all.order(:id)
    @statuses = Status.all
  end

  def detail
    job_id = params[:id]

    @job = Job.find(job_id)
    @stages = @job.stages.find_by(stage_no: @job.current_stage)
    # @stages = @job.stages.order(:stage_no)
    @statuses = Status.all
    @sands = Sand.all
  end

  def new_job
    @job = Job.create(:name => 'Job #' + (Job.maximum(:id).to_i+1).to_s, :current_stage => 1)
    @stage_count = 20 + rand(10)
    # start_time = Time.now.change(:usec => 0)
    @start_time = Time.now
    @stage_count.times do |j|
      @end_time = @start_time + 15 * 60
      @job.stages.create!(
          :stage_no => j+1,
          :status_id => Status.first.id,
          :start_time => @start_time,
          :end_time => @end_time,
          :completed => false,
          :sands => ''
      )
      @start_time = @end_time
    end
    @statuses = Status.all
  end

  def change_stage
    job_id = params[:job_id]
    stage_no = params[:stage_no]

    @result = "fail"

    @job = Job.find(job_id)
    @stages = @job.stages.find_by(stage_no: stage_no)
    @statuses = Status.all
    @sands = Sand.all
    if @job.present? && @stages.present?
      @result = "success"
    end

  end

  def complete
    job_id = params[:job_id]
    stage_no = params[:stage_no]
    status_id = params[:status_id]

    @result = "fail"
    @job = Job.find(job_id)
    @status = Status.find(status_id)

    if @job.present? && @status.present? && @job.current_stage == stage_no.to_i
      @result = "success"
      @job.complete_stage(stage_no, status_id)
      if @job.current_stage < @job.stages.count
        @job.current_stage += 1
      end
      @job.save!
      @stages = @job.stages.find_by(stage_no: stage_no.to_i+1)
      @sands = Sand.all
      @statuses = Status.all
      render 'change_stage'
    end
  end

  def update_status
    job_id = params[:job_id]
    stage_no = params[:stage_no]
    status_id = params[:status_id]

    @result = "fail"
    @job = Job.find(job_id)
    @status = Status.find(status_id)

    if @job.present? && @status.present? && @job.current_stage == stage_no.to_i
      @result = "success"
      @job.update_status(stage_no, status_id)
    end
  end

  def update_time
    job_id = params[:job_id]
    stage_no = params[:stage_no]
    add_time = params[:add_time]

    @result = "fail"
    @job = Job.find(job_id)

    if @job.present? && @job.current_stage == stage_no.to_i
      @result = "success"
      @job.update_time(stage_no, add_time.to_i)
      @next_stages = @job.stages.where("stage_no >= ?", stage_no).order(:stage_no)
      @stage = @job.stages.find_by(stage_no: stage_no)
    end
  end

  def add_sand
    job_id = params[:job_id]
    stage_no = params[:stage_no]
    sand_id = params[:sand_id]
    flag = params[:flag]

    @job = Job.find(job_id)

    if @job.present? && @job.current_stage == stage_no.to_i
      @result = "success"
      @job.add_sand(stage_no, sand_id, flag)
    end
  end

  def init_data
    if Status.count == 0
      Status.create!(:name => 'Pumping In Progress')
      Status.create!(:name => 'Pumping Is Down')

      job1 = Job.create(:name => 'Ham #18081', :current_stage => 1)
      stage_count = 52
      start_time = Time.now
      stage_count.times do |j|
        end_time = start_time + 3 * 60 * 60
        job1.stages.create!(
            :stage_no => j+1,
            :status_id => 1,
            :start_time => start_time,
            :end_time => end_time,
            :completed => false,
            :sands => ""
        )
        start_time = end_time
      end

      job2 = Job.create(:name => 'University land 09', :current_stage => 1)
      stage_count = 42
      start_time = Time.now
      stage_count.times do |j|
        end_time = start_time + 3 * 60 * 60
        job2.stages.create!(
            :stage_no => j+1,
            :status_id => 1,
            :start_time => start_time,
            :end_time => end_time,
            :completed => false,
            :sands => ""
        )
        start_time = end_time
      end

      job3 = Job.create(:name => 'Halfman 1214', :current_stage => 1)
      stage_count = 55
      start_time = Time.now
      stage_count.times do |j|
        end_time = start_time + 3 * 60 * 60
        job3.stages.create!(
            :stage_no => j+1,
            :status_id => 1,
            :start_time => start_time,
            :end_time => end_time,
            :completed => false,
            :sands => ""
        )
        start_time = end_time
      end

      Sand.create(:detail => '100 Mesh - White', :quantity => 125000)
      Sand.create(:detail => '100 Mesh - White', :quantity => 35000)
      Sand.create(:detail => '100 Mesh - White', :quantity => 52500)
      Sand.create(:detail => '40-70 Mesh - Texas Brite', :quantity => 42500)
      Sand.create(:detail => '40-70 Mesh - Texas Brite', :quantity => 53000)
      Sand.create(:detail => '40-70 Mesh - Texas Brite', :quantity => 31500)
      Sand.create(:detail => '40-70 Mesh - Texas Brite', :quantity => 10000)
      Sand.create(:detail => '40-70 Mesh - Preferred RCS', :quantity => 20000)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_job.html.erb
<li>
  <a href="/jobs/detail?id=<%= job.id %>" class="job">
    <span class="job-name">
        <%= job.name %>
    </span>
    <span class="stage">
        Stage <%= job.current_stage.to_s %> / <%= job.stages.count %> total
    </span>
    <%
       @current_stage = job.stages.find_by(:stage_no => job.current_stage)
       @status_id = @current_stage.status_id
    %>
    <span class="status<%= @status_id == 2 ? " error" : "" %>">
        <%
           concat statuses.find(@status_id).name
        %>
    </span>
  </a>
</li>

app/views/jobs/add_sand.js.erb
<% if @result == "success" %>

<% else %>
//alert('There is an error while processing your request.');
<% end %>

app/views/jobs/change_stage.js.erb
<% if @result == "success" %>
    $('#job-stages').html("<%= escape_javascript(render(:partial => @stages, :locals => {:sands => @sands})) %>");
    $('.dropdown').customSelect({
        customClass:'custom-dropdown'
    });

    $('.number').each(function(){
        var value = numberWithCommas($(this).html());
        $(this).html(numberWithCommas(value));
    });

    $('.checkbox').iCheck({
        checkboxClass: 'custom-checkbox'
    });
    $('.checkbox').iCheck('disable');
    $('.current-stage .checkbox').iCheck('enable');
    $('li.checked .checkbox').iCheck('check');
<% else %>

<% end %>

app/views/jobs/detail.html.erb
<header>
  <div class="width-container">
    <a href="#" id="logo">
    </a>

    <ul id="nav">
      <li>
        <%= link_to "All Jobs", jobs_path %>
      </li>
      <li>
        <%= link_to @job.name, '#', :class => "active" %>
      </li>
    </ul>

    <%= link_to "", jobs_path, :id => "back-button" %>
    <button id="mobile-menu-button"></button>

  </div>
</header>

<div id="job-tabs">
  <div class="width-container">
    <ul>
      <li>
        <a href="#" class="active">
          Overview
        </a>
      </li>
      <li>
        <a href="#">
          Full Schedule
        </a>
      </li>
      <li>
        <a href="#">
          Job Details
        </a>
      </li>
    </ul>
  </div>
</div>

<div class="container">
<div class="row">

<h1>
  Job Overview
</h1>

<div id="job-stages" job_id="<%= @job.id %>">
  <%= render :partial => @stages, :locals => {:sands => @sands} if @stages.present? %>
</div>

</div>

</div>
<div id="mobile-overlay">
  <ul id="dropdown-options"></ul>
</div>

app/views/jobs/index.html.erb
<header>
  <div class="width-container">
    <a href="#" id="logo">
    </a>

    <ul id="nav">
      <li>
        <%= link_to "All Jobs", jobs_path, :class => "active" %>
      </li>
    </ul>

    <button id="mobile-menu-button"></button>

  </div>
</header>
<div class="container" style="height: 100%">
  <div class="row">
    <button id="new-job-button" class="button">
      <span class="icon">+</span>
      New Job
    </button>

    <h1>
      All Jobs
    </h1>

  </div>

  <div class="row">
    <ul id="job-list">
      <%= render :partial => @jobs, :locals => {:statuses => @statuses} if @jobs.present? %>
    </ul>
  </div>

</div>

app/views/jobs/new_job.js.erb
$("#job-list").append('<%= escape_javascript(render :partial => @job, :locals => {:statuses => @statuses})%>')

app/views/jobs/update_status.js.erb
<% if @result == "success" %>
<% else %>
alert('There is an error while processing your request.');
<% end %>

app/views/jobs/update_time.js.erb
<% if @result == "success" %>
var current_stage = $('.current-stage');

// change current stage (completed)'s total time and percentage of elapsed time
<%
time_total = (@stage.end_time - @stage.start_time).to_i.abs / 3600.0
time_elapsed = (Time.now - @stage.start_time).to_i.abs / 3600.0
if time_total == 0.0
percentage = 0
else
percentage = (time_elapsed / time_total) * 100
percentage = percentage > 100 ? 100 : percentage
end
time_to_stage_complete = (@stage.end_time - Time.now).to_i
time_to_stage_complete = time_to_stage_complete < 0 ? 0 : time_to_stage_complete;
%>

current_stage.find('.elapsed #elapsed-time').html('<%= sprintf('%.2f', time_elapsed)%>')
current_stage.find('p.total').html('<%= sprintf('%.2f', time_total)%> <span>hrs</span>')
current_stage.find('.status-bar .bar').css('width', '<%=percentage%>%')

$(".current-stage .bar").stop();
//$(".current-stage .bar").animate({ width: "100%" }, <%=time_to_stage_complete * 1000%>);

// change next stages' start and end time
<% @next_stages.each { |stage| %>
current_stage.find('input.start_time').val("<%= stage.start_time %>");
current_stage.find('input.end_time').val("<%= stage.end_time %>");
current_stage.find('.start-time-day').html('<%= stage.start_time.strftime("%A %-m/%e") %>');
current_stage.find('.start-time').html('<%= stage.start_time.strftime("%H:%M") %>')
current_stage.find('.start-time-ampm').html('<%= stage.start_time.strftime("%P") %>')
current_stage.find('.end-time').html('<%= stage.end_time.strftime("%H:%M") %>')
current_stage.find('.end-time-ampm').html('<%= stage.end_time.strftime("%P") %>')
current_stage = current_stage.next();
<% }%>
<% else %>
alert('There is an error while processing your request.');
<% end %>
$('.current-stage .add-time, .current-stage .remove-time').removeClass('working')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <title>Pumping</title>
  <%= stylesheet_link_tag    'application-all', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application-all', 'data-turbolinks-track' => true %>

  <%= stylesheet_link_tag    'application-mobile', media: 'only screen and (max-width: 991px)', 'data-turbolinks-track' => true %>

  <!--[if lte IE 8]>
    <%= stylesheet_link_tag "application-ie8", :media => "all" %>
    <%= javascript_include_tag 'application-ie8', 'data-turbolinks-track' => true %>
<![endif]-->

  <!--[if lte IE 9]>
    <%= javascript_include_tag 'application-ie9', 'data-turbolinks-track' => true %>
<![endif]-->
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<script src="/assets/bootstrap.min.js" type="text/javascript"></script>
<script src="/assets/main.js" type="text/javascript"></script>
<script src="/assets/stage.js" type="text/javascript"></script>
<script src="/assets/check.js" type="text/javascript"></script>
</body>
</html>

app/views/stages/_stage.html.erb
<div class="job-stage<%= @job.current_stage > stage.stage_no ? " completed" : @job.current_stage < stage.stage_no ? " not-started" : " current-stage" %>" stage_no="<%= stage.stage_no %>">

  <h2>Stage <%= stage.stage_no%></h2>

  <div class="stage-nav">
    <button class="left">
      <span></span>
    </button>
    <button class="right">
      <span></span>
    </button>
  </div>

  <div class="status-container">
    <span>Status</span>

    <select class="dropdown">
      <%= render :partial => @statuses, :locals => {:current_status => stage.status_id} if @statuses.present? %>
    </select>
    <a class="update-status">
      update status
    </a>

    <div class="status-completed">
      <span class="status<%= stage.status_id == 2 ? " error" : "" %>"><%= @statuses.find(stage.status_id).name %></span>
      <span class="status-text">Complete</span>
    </div>

    <div class="status-not-started">
      <span class="status-text">Not Started</span>
    </div>

  </div>
  <div class="status-info">
    <div class="time-info">
      <span class="start-time-day">
        <%= stage.start_time.strftime("%A %-m/%e") %>
      </span>

      <p>
        <span>
            Start
        </span>
        <span class="start-time time">
            <%= stage.start_time.strftime("%H:%M") %>
        </span>
        <span class="start-time-ampm ampm">
            <%= stage.start_time.strftime("%P") %>
        </span>
      </p>

      <p>
        <span>
            End
        </span>
        <span class="end-time time">
            <%= stage.end_time.strftime("%H:%M") %>
        </span>
        <span class="end-time-ampm ampm">
            <%= stage.end_time.strftime("%P") %>
        </span>
      </p>

      <input type="hidden" class="start_time" value="<%= stage.start_time%>" />
      <input type="hidden" class="end_time" value="<%= stage.end_time%>" />

    </div>
    <div class="button-container">
      <div class="left">
        <button class="stage-complete-button button">
          Stage Complete
        </button>
      </div>
      <div class="right">
        <button class="remove-time">-</button>
        <button class="add-time">+</button>
        <span>Add/Remove Time</span>
      </div>
    </div>
  </div>
  <div class="status-bar">
    <p class="elapsed">
      <span id="elapsed-time">
      <% if @job.current_stage > stage.stage_no
        time_elapsed = (stage.end_time - stage.start_time).to_i.abs / 3600.0
        concat sprintf('%.2f', time_elapsed)
      end %>
      <% if @job.current_stage == stage.stage_no
        time_elapsed = (Time.now - stage.start_time).to_i.abs / 3600.0
        concat sprintf('%.2f', time_elapsed)
      end %>
      <% if @job.current_stage < stage.stage_no
        concat "0.00"
      end %>
      </span>
      <span>hrs</span>
    </p>

    <p class="total">
      <%
         time_total = (stage.end_time - stage.start_time).to_i.abs / 3600.0
         concat sprintf('%.2f', time_total)
      %>
      <span>hrs</span>
    </p>

    <div class="bar-outer">
      <% time_total = (stage.end_time - stage.start_time).to_i.abs / 1.0
         time_elapsed = (Time.now - stage.start_time).to_i.abs / 1.0
         if time_total == 0
           percentage = 0
         else
           percentage = (time_elapsed / time_total) * 100
           percentage = percentage > 100 ? 100 : percentage
         end
      %>
      <div class="bar" style="<%= @job.current_stage == stage.stage_no ? "width:"+percentage.to_s+"%" : "" %>;"></div>
    </div>

    <span class="elapsed">
        elapsed
    </span>

    <span class="total">
        total
    </span>
  </div>

  <div class="product-container">
    <h4>Sand</h4>

    <div>
      <p class="product-stats">
        Sand Total
        <span class="product-total number">
          <%= @sands.map(&:quantity).sum %>
        </span>
      </p>

      <% @stage_sands = stage.sands.split(',') %>
      <p class="product-stats">
        Sand Used
        <span class="product-used number">
          <%= @sands.select{ |item| @stage_sands.include?(item.id.to_s)}.map(&:quantity).sum %>
        </span>
      </p>

      <p class="product-stats">
        Sand Left
        <span class="product-left number">
          <%= @sands.select{ |item| !@stage_sands.include?(item.id.to_s)}.map(&:quantity).sum %>
        </span>
      </p>

    </div>

    <ul class="product-checklist">
      <li>
        Check when loaded to update totals
      </li>
      <% if @sands.present? %>
        <% @sands.each { |sand| %>
          <li sand_id="<%=sand.id%>" class="sand<%= @stage_sands.include?(sand.id.to_s) ? " checked":"" %>">
            <input type="checkbox" name="stage<%= stage.stage_no%>-cb<%=sand.id%>" id="stage<%= stage.stage_no%>-cb<%=sand.id%>" class="checkbox">
            <label for="stage<%= stage.stage_no%>-cb<%=sand.id%>" class="product-label">
              <span><%= sand.detail %></span>
              <span class="amount number"><%= sand.quantity %></span>
            </label>
          </li>
        <% } %>
      <% end %>
    </ul>
  </div>

  <% if @job.current_stage == stage.stage_no
     time_to_stage_complete = (stage.end_time - Time.now).to_i
     time_to_stage_complete = time_to_stage_complete < 0 ? 0 : time_to_stage_complete;
  %>
  <script>
    $(".current-stage .bar").animate({ width: "100%" }, <%=time_to_stage_complete * 1000%>);
  </script>
  <% end %>
</div>

app/views/statuses/_status.html.erb
<option value="<%= status.id %>" <%= status.id == current_status ? "selected" : "" %>><%= status.name %></option>